---

- name: Debian
  when: ansible_os_family == "Debian"
  block:
    - name: Debian | Ensure curl and gnupg are present
      ansible.builtin.package:
        name: [curl, gnupg]
        state: present

    - name: Debian | Add Microsoft APT key
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee {{ mde_apt_key_path }} > /dev/null
      args:
        executable: /bin/bash
        creates: "{{ mde_apt_key_path }}"

    - name: Add Microsoft apt repository for MDATP
      ansible.builtin.deb822_repository:
        name: "microsoft-{{ mde_channel }}"
        types: deb
        uris: "https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/{{ mde_channel }}"
        suites: "{{ ansible_distribution_release | lower }}"
        components:
          - main
        architectures: arm64,armhf,amd64
        signed_by: "{{ mde_apt_key_path }}"
      notify:
        - Update apt cache

- name: Add Microsoft DNF/YUM key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_os_family == "RedHat"

- name: Add  Microsoft yum repository for MDATP
  ansible.builtin.yum_repository:
    name: "packages-microsoft-{{ mde_channel }}"
    description: Microsoft Defender for Endpoint
    file: "microsoft-{{ mde_channel }}"
    baseurl: "https://packages.microsoft.com/rhel/{{ ansible_distribution_major_version }}/{{ mde_channel }}/"
    gpgcheck: yes
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    enabled: Yes
  when: ansible_os_family == "RedHat"
